#!/usr/bin/env python3

import argparse
import os
import yaml

import rclpy
from rclpy.node import Node
from trajectory_msgs.msg import JointTrajectory, JointTrajectoryPoint
from builtin_interfaces.msg import Duration


def load_yaml(path):
    path = os.path.expanduser(path)

    if not os.path.exists(path):
        raise RuntimeError(f"YAML file not found: {path}")

    with open(path, "r") as f:
        data = yaml.safe_load(f)

    return data if data is not None else {}


def load_active_joint_names(active_joint_names_yaml):
    data = load_yaml(active_joint_names_yaml)

    if "active_joint_names" not in data:
        raise RuntimeError(
            f"Missing key 'active_joint_names' in {active_joint_names_yaml}"
        )

    joint_names = data["active_joint_names"]

    if not isinstance(joint_names, list) or len(joint_names) == 0:
        raise RuntimeError("'active_joint_names' must be a non-empty list.")

    return joint_names


def load_manual_joint_goal(goal_yaml, goal_name, dof):
    data = load_yaml(goal_yaml)

    if "goals" not in data:
        raise RuntimeError(f"Missing top-level key 'goals' in {goal_yaml}")

    if goal_name not in data["goals"]:
        raise RuntimeError(f"Goal '{goal_name}' not found in {goal_yaml}")

    goal = data["goals"][goal_name]

    if "positions" not in goal:
        raise RuntimeError(f"Goal '{goal_name}' is missing required field 'positions'.")

    positions = goal["positions"]
    velocities = goal.get("velocities", [0.0] * dof)
    accelerations = goal.get("accelerations", [0.0] * dof)
    time_from_start = float(goal.get("time_from_start", 2.0))

    for field_name, values in [
        ("positions", positions),
        ("velocities", velocities),
        ("accelerations", accelerations),
    ]:
        if not isinstance(values, list):
            raise RuntimeError(f"'{field_name}' must be a list.")

        if len(values) != dof:
            raise RuntimeError(
                f"'{field_name}' length mismatch. "
                f"Expected {dof} values from active_joint_names.yaml, got {len(values)}."
            )

    return (
        [float(v) for v in positions],
        [float(v) for v in velocities],
        [float(v) for v in accelerations],
        time_from_start,
    )


class JointGoalSender(Node):
    def __init__(
        self,
        topic,
        joint_names,
        positions,
        velocities,
        accelerations,
        time_from_start,
        publish_rate_hz,
        publish_duration_sec,
    ):
        super().__init__("send_joint_goal")

        self.publisher = self.create_publisher(
            JointTrajectory,
            topic,
            10,
        )

        self.msg = JointTrajectory()
        self.msg.joint_names = joint_names

        point = JointTrajectoryPoint()
        point.positions = positions
        point.velocities = velocities
        point.accelerations = accelerations

        sec = int(time_from_start)
        nanosec = int((time_from_start - sec) * 1e9)
        point.time_from_start = Duration(sec=sec, nanosec=nanosec)

        self.msg.points.append(point)

        self.publish_count = 0
        self.max_publish_count = max(1, int(publish_rate_hz * publish_duration_sec))

        timer_period = 1.0 / publish_rate_hz
        self.timer = self.create_timer(timer_period, self.publish_once)

        self.get_logger().info(
            f"Publishing joint goal to '{topic}' at {publish_rate_hz:.2f} Hz "
            f"for {publish_duration_sec:.2f} s "
            f"({self.max_publish_count} messages)."
        )

    def publish_once(self):
        if self.publish_count >= self.max_publish_count:
            self.get_logger().info("Finished publishing joint goal.")
            rclpy.shutdown()
            return

        self.publisher.publish(self.msg)
        self.publish_count += 1

        self.get_logger().info(
            f"Published joint goal with {len(self.msg.joint_names)} joints "
            f"({self.publish_count}/{self.max_publish_count})."
        )


def main():
    parser = argparse.ArgumentParser(
        description="Publish one manual joint-space goal using runtime active_joint_names.yaml."
    )

    parser.add_argument(
        "--active-joint-names-yaml",
        required=True,
        help="Runtime YAML generated by smm_synthesis containing active_joint_names.",
    )

    parser.add_argument(
        "--goal-yaml",
        required=True,
        help="Manual joint goal YAML. Should contain numerical command values only.",
    )

    parser.add_argument(
        "--goal",
        required=True,
        help="Goal name inside the manual goal YAML.",
    )

    parser.add_argument(
        "--topic",
        default="/smm_joint_controller/reference",
        help="Controller reference topic.",
    )

    parser.add_argument(
        "--publish-rate-hz",
        type=float,
        default=2.0,
        help="Repeated publish rate in Hz.",
    )

    parser.add_argument(
        "--publish-duration-sec",
        type=float,
        default=3.0,
        help="How long to repeatedly publish the goal.",
    )

    args = parser.parse_args()

    joint_names = load_active_joint_names(args.active_joint_names_yaml)
    dof = len(joint_names)

    positions, velocities, accelerations, time_from_start = load_manual_joint_goal(
        goal_yaml=args.goal_yaml,
        goal_name=args.goal,
        dof=dof,
    )

    rclpy.init()

    node = JointGoalSender(
        topic=args.topic,
        joint_names=joint_names,
        positions=positions,
        velocities=velocities,
        accelerations=accelerations,
        time_from_start=time_from_start,
        publish_rate_hz=args.publish_rate_hz,
        publish_duration_sec=args.publish_duration_sec,
    )

    rclpy.spin(node)


if __name__ == "__main__":
    main()

# How to test:
# ros2 run smm_controllers send_joint_goal.py \
#  --active-joint-names-yaml ~/ros2_ws/src/smm_class_pkgs/smm_data/synthesis/yaml/active_joint_names.yaml \
#  --goal-yaml ~/ros2_ws/src/smm_class_pkgs/smm_control/smm_controllers/config/manual_commands/joint_goal_6dof.yaml \
#  --goal small_joint2_test