from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument, ExecuteProcess, TimerAction
from launch.substitutions import LaunchConfiguration

from ament_index_python.packages import get_package_share_directory

import os


def generate_launch_description():
    """
    Launch helper for joint-space command testing.

    This launch file is intended to be used AFTER the main Gazebo/control launch:

      ros2 launch smm_gazebo_sim spawn_smm_gazebo_control.launch.py \
        controller_type:=joint_inverse_dynamics \
        start_rqt_plot:=false

    Purpose:
      1. Start q-error plotting for /smm_joint_controller/q_error_i topics.
      2. Wait a short configurable delay so rqt_plot can open.
      3. Send a manual joint-space goal to /smm_joint_controller/reference.
      4. Stop the command sender when the joint position error becomes small.

    Notes:
      - Joint names are NOT hardcoded.
      - Joint names are loaded from the runtime active_joint_names.yaml generated by smm_synthesis.
      - The manual goal YAML contains only numerical command values.
      - This launch file is for validation/debugging of joint-space controllers.
      - It does not spawn the robot; use it alongside the main smm_gazebo_sim launch.
    """

    smm_controllers_share = get_package_share_directory("smm_controllers")

    default_active_joint_names_yaml = os.path.expanduser(
        "~/ros2_ws/src/smm_class_pkgs/smm_data/synthesis/yaml/active_joint_names.yaml"
    )

    default_goal_yaml = os.path.join(
        smm_controllers_share,
        "config",
        "manual_commands",
        "joint_goal_6dof.yaml",
    )

    active_joint_names_yaml_arg = DeclareLaunchArgument(
        "active_joint_names_yaml",
        default_value=default_active_joint_names_yaml,
        description="Runtime YAML generated by smm_synthesis containing active_joint_names.",
    )

    goal_yaml_arg = DeclareLaunchArgument(
        "goal_yaml",
        default_value=default_goal_yaml,
        description="Manual joint goal YAML containing numerical command values only.",
    )

    goal_arg = DeclareLaunchArgument(
        "goal",
        default_value="small_joint2_test",
        description="Goal name inside the manual joint goal YAML.",
    )

    controller_name_arg = DeclareLaunchArgument(
        "controller_name",
        default_value="smm_joint_controller",
        description="Controller name used for reference and q_error topics.",
    )

    publish_rate_arg = DeclareLaunchArgument(
        "publish_rate_hz",
        default_value="5.0",
        description="Repeated command publish rate in Hz.",
    )

    publish_duration_arg = DeclareLaunchArgument(
        "publish_duration_sec",
        default_value="10.0",
        description="Maximum duration for repeated command publishing.",
    )

    error_tolerance_arg = DeclareLaunchArgument(
        "error_tolerance",
        default_value="0.01",
        description="Max absolute joint position error tolerance in radians.",
    )

    stable_time_arg = DeclareLaunchArgument(
        "stable_time_sec",
        default_value="0.5",
        description="Time for which error must remain below tolerance before command sender exits.",
    )

    timeout_arg = DeclareLaunchArgument(
        "timeout_sec",
        default_value="12.0",
        description="Maximum command execution wait time when stop-on-error is enabled.",
    )

    command_delay_arg = DeclareLaunchArgument(
        "command_delay_sec",
        default_value="2.0",
        description="Delay before sending command, giving rqt_plot time to open.",
    )

    # -------------------------------------------------------------------------
    # 1) Start q-error plotting first.
    #
    # The plotting script reads active_joint_names.yaml, infers the current DOF,
    # waits for q_error topics, and opens rqt_plot with:
    #
    #   /<controller_name>/q_error_0/data
    #   ...
    #   /<controller_name>/q_error_N/data
    #
    # Starting it before the command helps capture the full error transient.
    # -------------------------------------------------------------------------
    plot_joint_pos_error = ExecuteProcess(
        cmd=[
            "ros2",
            "run",
            "smm_controllers",
            "plot_joint_pos_error.py",
            "--active-joint-names-yaml",
            LaunchConfiguration("active_joint_names_yaml"),
            "--controller-name",
            LaunchConfiguration("controller_name"),
        ],
        output="screen",
    )

    # -------------------------------------------------------------------------
    # 2) Define the command sender.
    #
    # It publishes a JointTrajectory command to:
    #
    #   /<controller_name>/reference
    #
    # It also monitors:
    #
    #   /<controller_name>/q_error_i
    #
    # and exits when max(|q_error_i|) < error_tolerance for stable_time_sec.
    # -------------------------------------------------------------------------
    send_joint_goal = ExecuteProcess(
        cmd=[
            "ros2",
            "run",
            "smm_controllers",
            "send_joint_goal_error_fdbk.py",
            "--active-joint-names-yaml",
            LaunchConfiguration("active_joint_names_yaml"),
            "--goal-yaml",
            LaunchConfiguration("goal_yaml"),
            "--goal",
            LaunchConfiguration("goal"),
            "--topic",
            ["/", LaunchConfiguration("controller_name"), "/reference"],
            "--controller-name",
            LaunchConfiguration("controller_name"),
            "--publish-rate-hz",
            LaunchConfiguration("publish_rate_hz"),
            "--publish-duration-sec",
            LaunchConfiguration("publish_duration_sec"),
            "--stop-on-error",
            "--error-tolerance",
            LaunchConfiguration("error_tolerance"),
            "--stable-time-sec",
            LaunchConfiguration("stable_time_sec"),
            "--timeout-sec",
            LaunchConfiguration("timeout_sec"),
        ],
        output="screen",
    )

    # -------------------------------------------------------------------------
    # 3) Send the command after a small delay.
    #
    # This delay is only for visualization: it gives rqt_plot time to open before
    # the command transient begins. It is not used for controller synchronization.
    # -------------------------------------------------------------------------
    delayed_send_joint_goal = TimerAction(
        period=LaunchConfiguration("command_delay_sec"),
        actions=[
            send_joint_goal,
        ],
    )

    return LaunchDescription(
        [
            active_joint_names_yaml_arg,
            goal_yaml_arg,
            goal_arg,
            controller_name_arg,
            publish_rate_arg,
            publish_duration_arg,
            error_tolerance_arg,
            stable_time_arg,
            timeout_arg,
            command_delay_arg,
            plot_joint_pos_error,
            delayed_send_joint_goal,
        ]
    )